### ISSUE TITLE
Download data section in the first page

### ISSUE THREAD

**Issue by allikah1** [phax/phoss-directory#11]
Can we have download data section in first page with some filtering opportunities:
- country of receiving
- ID type of the participant
- ???

**Comment by phax** [comment]
In general this is a good idea, but I'm not sure, whether this will be avialable in the first version. The constraints need to be defined, by which a filtering can be done.
Alternatively an Excel file could be made available, where you can filter yourself quite easily....

**Comment by allikah1** [comment]
Agree. Not needed in the first phase

**Comment by Moellre** [comment]
I think the download function is good, but when seeing how its "missused" as with ELMA, I really see this as future functionallity.

**Comment by phax** [comment]
Especially because it is "misused" it must be provided early. The "future" part of this issus imho, the filtering.
I'd really like to give away "all" data asap, so that the crawling is avoided!

**Comment by phax** [comment]
All participant data can be publically downloaded
