### ISSUE TITLE
Support libray for converting JPA Entity (SMP_BCE) to PD1BusinessCardType

### ISSUE THREAD

**Issue by ssinatti** [phax/phoss-directory#26]
Good morning Philip,

I would like to  convert my local java entity (JPA) SmpBce as PD1BusinessCardType object, probably you have implemented a sort of manager/helper in order to manage it, haven't you? 

Thank you in advance.

Stefano

**Comment by phax** [comment]
Hi Stefano!
You want to convert a `com.helger.peppol.smpserver.data.sql.model.DBBusinessCardEntity` to a `com.helger.pd.businesscard.v1.PD1BusinessCardType`?
The conversion for this is implemented in `com.helger.peppol.smpserver.domain.businesscard.SMPBusinessCard.getAsJAXBObject()`.

hth, Philip
