### ISSUE TITLE
Allow multiple names in different languages in the business card data model

### ISSUE THREAD

**Issue by florentbabelway** [phax/phoss-directory#32]
Belgian participant can have entity names in four different languages (FR, EN, NL, DE), and we need to push all of those names to Peppol Directory.

The current business card model does not allow to publish more than one name.

The first workaround we thought was to concatenate all of these names in the tag <Name>. However, there comes some politics issues:
Which language do we publish first? If we publish NL, French speaking people will not agree... If we publish FR first, NL people won't agree...

I would like to suggest to update the business card to allow multiple <Name> tag and add an optional "language" attribute on it. 
For example:

```
<Name language="FR">...</Name>
<Name language="EN">...</Name>
<Name language="DE">...</Name>
<Name language="NL">...</Name>
```

**Comment by phax** [comment]
The official PEPPOL issue is https://openpeppol.atlassian.net/browse/TICC-30

**Comment by phax** [comment]
As this has implications to the data model (also of the SMP), an intermediate solution must be found.
* By adding all names in a row, e.g. separated by a dash or so
* By adding links to the Belgium official pages with all names (for now)

**Comment by phax** [comment]
This is implemented with Business Card data model v3
