### ISSUE TITLE
REST API Response header parameter total-result-count is not counting all the matching entries

### ISSUE THREAD

**Issue by anakinj** [phax/phoss-directory#39]
Hi,

Noticed a small issue with the Directory REST API related to the total-result-count not actually being what it advertises.

For example when using the UI and querying for the word "test" it says that there are around 3000 hits. https://test-directory.peppol.eu/public/locale-en_US/menuitem-search?q=test

But doing that same query using the API, the total is always just the size of the result set.
https://test-directory.peppol.eu/search/1.0/json?q=test&rpc=1
https://test-directory.peppol.eu/search/1.0/json?q=test&rpc=50

This makes it impossible to actually know when paging should be applied.

Think the API implementation needs to do a explicit count for the query, as the UI is doing here: https://github.com/phax/phoss-directory/blob/master/phoss-directory-publisher/src/main/java/com/helger/pd/publisher/app/pub/page/PagePublicSearchSimple.java#L162

**Comment by phax** [comment]
Fixed in 0.8.0 release - thanks for pointing out. Will try to get it on the test server asap.

**Comment by anakinj** [comment]
Great! Thanks for the super-fast response.
