### ISSUE TITLE
Can the PDBC export also include supported doc types capabilities?

### ISSUE THREAD

**Issue by clancger** [phax/phoss-directory#41]
Today, an export of the PDBC data only covers the Business Information content, and does not include the supported document types from the 2nd tab.

Is it possible to include this info in the export? 
Otherwise, if I'm comparing a list of entities, I can only see which of them have "some" PEPPOL capability, but will need to look them up separately, and individually to discover which ones can support a particular doc type. 
If a participant already has PEPPOL capabilities, and adds a new doc type (e.g BIS3), then only an individual paticipant-level search will show this.

**Comment by phax** [comment]
Contained in next deployment. Attention: the XSD changed, so there is a new namespace and a new version!
