### ISSUE TITLE
Include regDate field in export data

### ISSUE THREAD

**Issue by readethompsontrott** [phax/phoss-directory#45]
Hi @phax, can you please include the regDate field in the downloadable exports?

**Comment by phax** [comment]
Sure. Will add it to the next release. Good input. Thx

**Comment by phax** [comment]
Will be part of the 0.8.5 release. Thanks.

**Comment by readethompsontrott** [comment]
Thanks @phax. Much appreciated. Any indication of a release date?

**Comment by phax** [comment]
Nope not yet. We're currently quite busy with the AS4 stuff, so I cannot promise anything, but I will try to do it within the next 2 weeks. hth
