### ISSUE TITLE
Improve Directory XML file quality 

### ISSUE THREAD

**Issue by allikah1** [phax/phoss-directory#46]
I would propose that Peppol Directory XML dump file is either containing a flag regarding if document type under discussion belongs to Peppol supported list (meaning it is standard) or it ain't standard type.

**Comment by phax** [comment]
Is part of the 0.8.5 release, but only in the full XML export.
The `doctypeid` element was extended:
* Either the attribute `non-standard`  with value `true` is contained or
* the attribute `displayname` and the attribute `deprecated`
