### ISSUE TITLE
How to limit PDBC exports to a county / countries?

### ISSUE THREAD

**Issue by clancger** [phax/phoss-directory#53]
If I want to download only the Business Cards for 1 country, (eg Australia), what is the best way to do so?
There are approx 7135 individual Australian entities listed, based on a full export on Sept 17
Is there any other way apart from doing a full export, and then filtering from there?

From PD Search..
"Australia" appears 288 times, but includes entities in SG and NZ with Australia in the name.
"AU" appears 29,024 times as following the letter sequence
"0151" appears 7,923 times ..anywhere that number sequence appears
"0151:" appears also 7,923 times ..so the colon doesnt limit

**Comment by phax** [comment]
Hi @clancger  unfortunately not  - I am sorry. But this is - as usual - a good suggestion for improvement. We may just add an export "per country".
