### ISSUE TITLE
The csv export containing doctypes, is missing commas between doctypes where several exist

### ISSUE THREAD

**Issue by clancger** [phax/phoss-directory#55]
in the Export, containing Doctypes, it seems that when a participant supports more than 1 doctype, these are not comma-separated, so that opening the csv in excel just appends all the doctypes as a long string in 1 column..for example

"iso6523-actorid-upis::0151:92559803626";"The Trustee for DCM TRUST";"AU";;"";"";"";"";"";"";"";;"2021-09-24";"busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2::ApplicationResponse##urn:fdc:peppol.eu:poacc:trns:invoice_response:3::2.1
busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:ApplicationResponse-2::ApplicationResponse##urn:fdc:peppol.eu:poacc:trns:mlr:3::2.1
busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:CreditNote-2::CreditNote##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1
busdox-docid-qns::urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#conformant#urn:fdc:peppol.eu:2017:poacc:billing:international:aunz:3.0::2.1"

**Comment by phax** [comment]
Hi @clancger, the document types are newline separated.
The reason is, that the number of document types is basically unlimited and having a dynamic amount of columns is hard to work with.
So it was decided to use "\n" as the separator within one cell
