### ISSUE TITLE
Is this directory expanded to list senders too?

### ISSUE THREAD

**Issue by kirti2001** [phax/phoss-directory#57]

**Comment by phax** [comment]
Copy from answer zo  #20:
> Every sender can already today register today in the Directory. It's just not technically mandatory for senders to register, but it is possible.
Just register a service group and than add the Business Card in the SMP.

**Comment by phax** [comment]
The introduction of mandatory MLR in certain jurisdictions will make senders to receivers and than they have it easier to register in the Directory in a consistent way.
