### ISSUE TITLE
Supported versions of business card data model

### ISSUE THREAD

**Issue by tmhide** [phax/phoss-directory#62]
There is a business card data model v3, but I don't think phoss-smp and Peppol Directory support this.
Is the version that phoss-smp and Peppol Directory support v2?
https://github.com/phax/phoss-directory/tree/master/phoss-directory-businesscard/src/main/resources/schemas

**Comment by tmhide** [comment]
Uh, phoss-smp and Peppol Directory support v1?
What are v2 and v3 for?

**Comment by phax** [comment]
Well phoss SMP does support Business Card v3, but on the GUI it does not allow you to provide a language.
So if you import the Business Card via the API including a `Name` with a `lanaguege` that should (I have not tested it) be persisted and provided when queried.

**Comment by tmhide** [comment]
I tried PUT /businesscard/{participantIdentifier}, but the language attribute did not register.
According to the following implementation, phoss-smp does not support Business Card v3 via the API.

https://github.com/phax/phoss-smp/blob/7ceec53f9cecef3f012af5150de46ff5c57848f7/phoss-smp-backend-sql/src/main/java/com/helger/phoss/smp/backend/sql/mgr/SMPBusinessCardManagerJDBC.java#L212

I tried the following update query, but GET /businesscard/{participantIdentifier} did not output in Business Card v3 format.
```
update smp_bce set  name = '[{"name":"test","language":"en"}]' where id = 'idxxx'
```

I would like to see support for MultilingualNameType even if it is only for the REST API (GET/PUT), do you have any plans?

**Comment by phax** [comment]
@tmhide sure, that should work. May I ask you to copy the content of your last request to a ticket at https://github.com/phax/phoss-smp/issues - thanks.

**Comment by phax** [comment]
Thank for this. Closing this ticket here.
