### ISSUE TITLE
Add CORS support to REST API

### ISSUE THREAD

**Issue by swftvsn** [phax/phoss-directory#68]
Hi,

we'd like to use the API to validate the address the user inputs in our system. This is done in the client in browser and is now blocked due to missing CORS headers.

Please add `Access-Control-Allow-Origin: *` header to API response, if the API is considered to be open to use to enable the usage directly from browser apps.

Thank you!

**Comment by phax** [comment]
Yes makes sense. Thanks for the hint

**Comment by phax** [comment]
Implemented in the upcomoing 0.13.5 version. I don't know when it will be deployed on Peppol servers. Please consult the Peppol Service Desk for that matter - thanks :)
